version: '3.3'

services:

  app:
    build: .
    container_name: graphapp
    restart: always
    depends_on:
      - neo4j
    ports:
      - "5000:5000"
    command: python main.py
    networks:
      - graph_network

  neo4j:
    image: neo4j:4.3.7-enterprise
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
       - ./data:/data
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes 
      - NEO4J_AUTH=*/*
    networks:
      - graph_network

  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter
    restart: always
    depends_on:
      - neo4j
    ports:
      - "8888:8888"
    networks:
      - graph_network

networks:
  graph_network:
    name: graph_network



  
    